spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//oracle-db:1521/XEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:airwatch}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:airwatch123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
airwatch.jwt.secret=${AIRWATCH_JWT_SECRET:AirWatchSolsticioFIAP2026SecretKeyBase64EncodedMinimo256bits}
airwatch.jwt.expiration=${AIRWATCH_JWT_EXPIRATION:86400000}
server.port=${PORT:8080}
springdoc.default-flat-param-object=true
