spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
spring.datasource.username=RM565760
spring.datasource.password=150606
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
airwatch.jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9ae8b7c6d5e4f3a2b1c0e9f8a7b6c5d4e3f2
airwatch.jwt.expiration=86400000
springdoc.default-flat-param-object=true