spring.application.name=airwatch
spring.profiles.active=fiap
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
airwatch.jwt.secret=AirWatchSolsticioFIAP2026SecretKeyBase64EncodedMinimo256bits
airwatch.jwt.expiration=86400000
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
server.port=${PORT:8080}
springdoc.default-flat-param-object=true
